# Generated by Django 3.2 on 2021-04-08 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desk_num', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('IS_MANAGER', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Service_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
                ('Image', models.ImageField(blank=True, upload_to='images/service_center/', verbose_name='Image')),
                ('Icon', models.ImageField(blank=True, upload_to='images/service_center/Icon/', verbose_name='icon')),
                ('QR', models.ImageField(blank=True, upload_to='images/service_center/QR/', verbose_name='QR')),
            ],
        ),
        migrations.CreateModel(
            name='Work_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saturday', models.CharField(max_length=500)),
                ('Sunday', models.CharField(max_length=500)),
                ('Monday', models.CharField(max_length=500)),
                ('Tuesday', models.CharField(max_length=500)),
                ('Wednesday', models.CharField(max_length=500)),
                ('Thursday', models.CharField(max_length=500)),
                ('Friday', models.CharField(max_length=500)),
                ('Service_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
            ],
        ),
        migrations.CreateModel(
            name='White_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=600)),
                ('Service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System_Black_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=600)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IQ_Time', models.DateTimeField(auto_now_add=True)),
                ('P_Time', models.DateTimeField(auto_now_add=True)),
                ('O_Time', models.DateTimeField(auto_now_add=True)),
                ('IS_InCenter', models.BooleanField(default=False)),
                ('Queue_type', models.CharField(choices=[('A', 'Has a priority'), ('B', 'Has no a priority ')], default='B', max_length=1)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.employee')),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='Service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Service_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service_center'),
        ),
        migrations.CreateModel(
            name='Black_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=600)),
                ('Service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
