# Generated by Django 3.1.3 on 2021-03-16 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('IS_MANAGER', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('number_of_provider', models.IntegerField()),
                ('time_of_provid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('location', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
                ('QR', models.ImageField(blank=True, upload_to='images/service_center/QR/', verbose_name='QR')),
                ('Image', models.ImageField(blank=True, upload_to='images/service_center/', verbose_name='Image')),
                ('Icon', models.ImageField(blank=True, upload_to='images/service_center/Icon/', verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Work_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sunday', models.CharField(max_length=300)),
                ('Monday', models.CharField(max_length=300)),
                ('Tuesday', models.CharField(max_length=300)),
                ('Wednesday', models.CharField(max_length=300)),
                ('Thursday', models.CharField(max_length=300)),
                ('Friday', models.CharField(max_length=300)),
                ('Saturday', models.CharField(max_length=300)),
                ('Service_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
            ],
        ),
        migrations.CreateModel(
            name='White_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.employee')),
                ('Service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Accepted', models.BooleanField(default=False)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.employee')),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='Service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Service_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service_center'),
        ),
        migrations.CreateModel(
            name='Black_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.employee')),
                ('Service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
