# Generated by Django 3.2 on 2021-04-18 15:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
                ('Image', models.ImageField(blank=True, upload_to='service_center/', verbose_name='Image')),
                ('Icon', models.ImageField(blank=True, upload_to='service_center/Icon/', verbose_name='icon')),
                ('QR', models.ImageField(blank=True, upload_to='service_center/QR/', verbose_name='QR')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_employee', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QMS_app.user')),
                ('desk_num', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Work_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saturday', models.CharField(max_length=500)),
                ('Sunday', models.CharField(max_length=500)),
                ('Monday', models.CharField(max_length=500)),
                ('Tuesday', models.CharField(max_length=500)),
                ('Wednesday', models.CharField(max_length=500)),
                ('Thursday', models.CharField(max_length=500)),
                ('Friday', models.CharField(max_length=500)),
                ('Service_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
            ],
        ),
        migrations.CreateModel(
            name='White_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=600)),
                ('Service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System_Black_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=600)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('IS_Active', models.BooleanField(default=True)),
                ('Service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
            ],
        ),
        migrations.CreateModel(
            name='Black_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=600)),
                ('Service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IQ_Time', models.DateTimeField(auto_now_add=True)),
                ('P_Time', models.DateTimeField(auto_now_add=True)),
                ('O_Time', models.DateTimeField(auto_now_add=True)),
                ('IS_InCenter', models.BooleanField(default=False)),
                ('Queue_type', models.CharField(choices=[('A', 'Has a priority'), ('B', 'Has no a priority ')], default='B', max_length=1)),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QMS_app.user')),
                ('Service_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service_center')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Service_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.service_center'),
        ),
    ]
