# Generated by Django 3.2 on 2021-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='IS_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='Icon',
            field=models.ImageField(blank=True, upload_to='service_center/Icon/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='Image',
            field=models.ImageField(blank=True, upload_to='service_center/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='QR',
            field=models.ImageField(blank=True, upload_to='service_center/QR/', verbose_name='QR'),
        ),
    ]
