# Generated by Django 3.1.7 on 2021-04-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='white_list',
            name='reason',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
