# Generated by Django 3.1.7 on 2021-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0002_auto_20210429_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_record',
            name='is_accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service_record',
            name='is_served',
            field=models.BooleanField(default=True),
        ),
    ]
