# Generated by Django 3.1.7 on 2021-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0004_auto_20210429_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_record',
            name='O_Time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='service_record',
            name='P_Time',
            field=models.DateTimeField(blank=True),
        ),
    ]
