# Generated by Django 3.1.7 on 2021-04-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0007_user_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='black_list',
            name='reason',
        ),
    ]
