# Generated by Django 3.1.7 on 2021-04-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0008_remove_black_list_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_center',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
