# Generated by Django 3.1.7 on 2021-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0009_service_center_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Friday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Monday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Saturday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Sunday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Thursday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Tuesday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Wednesday',
            field=models.CharField(max_length=200),
        ),
    ]
