# Generated by Django 3.1.7 on 2021-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0010_auto_20210501_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_center',
            name='mapLocations',
            field=models.CharField(blank=True, db_column='field_three', default='', max_length=500),
        ),
    ]
