# Generated by Django 3.1.7 on 2021-05-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0011_service_center_maplocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='Icon',
            field=models.ImageField(default='service_center/Icon/default-logo.png', upload_to='service_center/Icon/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='Image',
            field=models.ImageField(default='service_center/default-image.jpg', upload_to='service_center/', verbose_name='Image'),
        ),
    ]
