# Generated by Django 3.1.7 on 2021-05-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0012_auto_20210501_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_center',
            name='is_cancelled',
            field=models.BooleanField(default=True),
        ),
    ]
