# Generated by Django 3.1.7 on 2021-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0014_auto_20210501_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='mapLocations',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
