# Generated by Django 3.1.7 on 2021-05-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0015_auto_20210501_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_center',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='service_record',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
