# Generated by Django 3.1.7 on 2021-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0016_auto_20210501_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='black_list',
            name='reason',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
