# Generated by Django 3.2 on 2021-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0017_black_list_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
