# Generated by Django 3.2 on 2021-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0018_alter_service_center_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
