# Generated by Django 3.2 on 2021-05-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0019_alter_service_center_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.user'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
        migrations.AlterField(
            model_name='white_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS_app.user'),
        ),
    ]
