# Generated by Django 3.2 on 2021-05-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0020_auto_20210507_1431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('Service_center', 'desk_num')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('Service_center', 'name')},
        ),
    ]
