# Generated by Django 3.1.7 on 2021-05-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0021_auto_20210511_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='black_list',
            name='is_BySystem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='black_list',
            name='Service_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
        migrations.DeleteModel(
            name='System_Black_list',
        ),
    ]
