# Generated by Django 3.1.7 on 2021-05-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0022_auto_20210511_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_list',
            name='Service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_app.service_center'),
        ),
    ]
