# Generated by Django 3.1.7 on 2021-05-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0023_auto_20210512_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.CharField(default='5 min', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_center',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
