# Generated by Django 3.2 on 2021-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0024_auto_20210518_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_record',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
