# Generated by Django 3.2 on 2021-05-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0025_service_record_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_time',
            name='Friday',
            field=models.CharField(default=' no data ', max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Monday',
            field=models.CharField(default=' no data ', max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Saturday',
            field=models.CharField(default=' no data ', max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Sunday',
            field=models.CharField(default=' no data ', max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Thursday',
            field=models.CharField(default=' no data ', max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Tuesday',
            field=models.CharField(default=' no data ', max_length=200),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='Wednesday',
            field=models.CharField(default=' no data ', max_length=200),
        ),
    ]
