# Generated by Django 3.1.7 on 2021-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0026_auto_20210524_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
