# Generated by Django 3.1.7 on 2021-07-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0028_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_text',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
