# Generated by Django 3.1.7 on 2021-07-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0029_message_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_file',
        ),
    ]
