# Generated by Django 3.1.7 on 2021-07-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0030_remove_message_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='unread',
        ),
    ]
