# Generated by Django 3.1.7 on 2021-07-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0032_auto_20210716_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='IS_read',
            field=models.BooleanField(default=False),
        ),
    ]
