# Generated by Django 3.1.7 on 2021-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0033_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_record',
            name='is_accept',
        ),
        migrations.AddField(
            model_name='service_record',
            name='status',
            field=models.CharField(choices=[('A', 'accepted'), ('p', 'pending'), ('R', 'rejected')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
