# Generated by Django 3.1.7 on 2021-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0034_auto_20210725_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_center',
            name='isAutoAccept',
            field=models.BooleanField(default=True),
        ),
    ]
