# Generated by Django 3.2 on 2021-07-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0035_service_center_isautoaccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_record',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.employee'),
        ),
        migrations.AlterField(
            model_name='service_record',
            name='status',
            field=models.CharField(choices=[('A', 'accepted'), ('P', 'pending'), ('R', 'rejected')], max_length=1),
        ),
    ]
