# Generated by Django 3.1.7 on 2021-07-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0036_auto_20210726_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
