# Generated by Django 3.1.7 on 2021-07-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0037_auto_20210726_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='IS_static',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='defaultTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
