# Generated by Django 3.1.7 on 2021-08-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0038_auto_20210727_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='EmpMessage',
        ),
    ]
