# Generated by Django 3.2 on 2021-08-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0039_auto_20210801_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QMS_app.employee'),
        ),
    ]
