# Generated by Django 3.2 on 2021-08-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0040_alter_empmessage_receiver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='black_list',
            unique_together={('Service_center', 'user')},
        ),
    ]
