# Generated by Django 3.2 on 2021-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_app', '0041_alter_black_list_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='black_list',
            unique_together=set(),
        ),
    ]
